"""initial_phase1_schema

Revision ID: 53b46285e442
Revises: 
Create Date: 2026-09-03 21:46:35.260727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b46285e442'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('run_id', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_public_id'), 'audit_events', ['public_id'], unique=True)
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_run_id'), 'audit_events', ['run_id'], unique=False)
    op.create_table('ngos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngos_external_id'), 'ngos', ['external_id'], unique=True)
    op.create_index(op.f('ix_ngos_name'), 'ngos', ['name'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('budget_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculation_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_predicted_impact', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_public_id'), 'optimization_runs', ['public_id'], unique=True)
    op.create_index(op.f('ix_optimization_runs_status'), 'optimization_runs', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('due_diligence_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=False),
    sa.Column('overall_status', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_due_diligence_reports_ngo_id'), 'due_diligence_reports', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_due_diligence_reports_overall_status'), 'due_diligence_reports', ['overall_status'], unique=False)
    op.create_index(op.f('ix_due_diligence_reports_public_id'), 'due_diligence_reports', ['public_id'], unique=True)
    op.create_index(op.f('ix_due_diligence_reports_risk_level'), 'due_diligence_reports', ['risk_level'], unique=False)
    op.create_table('proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('ngo_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposals_ngo_id'), 'proposals', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_proposals_public_id'), 'proposals', ['public_id'], unique=True)
    op.create_index(op.f('ix_proposals_status'), 'proposals', ['status'], unique=False)
    op.create_table('reallocation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('previous_optimization_id', sa.UUID(), nullable=False),
    sa.Column('budget_paise', sa.BigInteger(), nullable=False),
    sa.Column('performance_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calculation_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['previous_optimization_id'], ['optimization_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reallocation_runs_previous_optimization_id'), 'reallocation_runs', ['previous_optimization_id'], unique=False)
    op.create_index(op.f('ix_reallocation_runs_public_id'), 'reallocation_runs', ['public_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_proposal_id'), 'documents', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_documents_public_id'), 'documents', ['public_id'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=True),
    sa.Column('ngo_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('requested_amount', sa.BigInteger(), nullable=False),
    sa.Column('current_funding', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ngo_id'], ['ngos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_ngo_id'), 'projects', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_projects_proposal_id'), 'projects', ['proposal_id'], unique=False)
    op.create_index(op.f('ix_projects_public_id'), 'projects', ['public_id'], unique=True)
    op.create_index(op.f('ix_projects_sector'), 'projects', ['sector'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('optimization_run_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('allocated_amount', sa.BigInteger(), nullable=False),
    sa.Column('marginal_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('base_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('saturation_index', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reason_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_optimization_run_id'), 'allocations', ['optimization_run_id'], unique=False)
    op.create_index(op.f('ix_allocations_project_id'), 'allocations', ['project_id'], unique=False)
    op.create_index(op.f('ix_allocations_status'), 'allocations', ['status'], unique=False)
    op.create_table('impact_dna',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('need_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('expected_impact_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('cost_efficiency_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('evidence_strength_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('scalability_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('implementation_risk_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('beneficiary_reach', sa.BigInteger(), nullable=True),
    sa.Column('estimated_impact_per_lakh', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_dna_project_id'), 'impact_dna', ['project_id'], unique=True)
    op.create_index(op.f('ix_impact_dna_public_id'), 'impact_dna', ['public_id'], unique=True)
    op.create_table('project_geographies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('block', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_geographies_district'), 'project_geographies', ['district'], unique=False)
    op.create_index(op.f('ix_project_geographies_project_id'), 'project_geographies', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_geographies_state'), 'project_geographies', ['state'], unique=False)
    op.create_table('saturation_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=50), nullable=False),
    sa.Column('saturation_index', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('need_score', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('existing_csr_amount', sa.BigInteger(), nullable=True),
    sa.Column('beneficiary_coverage', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('calculation_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saturation_results_project_id'), 'saturation_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_saturation_results_sector'), 'saturation_results', ['sector'], unique=False)
    op.create_index(op.f('ix_saturation_results_state'), 'saturation_results', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saturation_results_state'), table_name='saturation_results')
    op.drop_index(op.f('ix_saturation_results_sector'), table_name='saturation_results')
    op.drop_index(op.f('ix_saturation_results_project_id'), table_name='saturation_results')
    op.drop_table('saturation_results')
    op.drop_index(op.f('ix_project_geographies_state'), table_name='project_geographies')
    op.drop_index(op.f('ix_project_geographies_project_id'), table_name='project_geographies')
    op.drop_index(op.f('ix_project_geographies_district'), table_name='project_geographies')
    op.drop_table('project_geographies')
    op.drop_index(op.f('ix_impact_dna_public_id'), table_name='impact_dna')
    op.drop_index(op.f('ix_impact_dna_project_id'), table_name='impact_dna')
    op.drop_table('impact_dna')
    op.drop_index(op.f('ix_allocations_status'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_project_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_optimization_run_id'), table_name='allocations')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_projects_sector'), table_name='projects')
    op.drop_index(op.f('ix_projects_public_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_proposal_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_ngo_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_documents_public_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_proposal_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reallocation_runs_public_id'), table_name='reallocation_runs')
    op.drop_index(op.f('ix_reallocation_runs_previous_optimization_id'), table_name='reallocation_runs')
    op.drop_table('reallocation_runs')
    op.drop_index(op.f('ix_proposals_status'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_public_id'), table_name='proposals')
    op.drop_index(op.f('ix_proposals_ngo_id'), table_name='proposals')
    op.drop_table('proposals')
    op.drop_index(op.f('ix_due_diligence_reports_risk_level'), table_name='due_diligence_reports')
    op.drop_index(op.f('ix_due_diligence_reports_public_id'), table_name='due_diligence_reports')
    op.drop_index(op.f('ix_due_diligence_reports_overall_status'), table_name='due_diligence_reports')
    op.drop_index(op.f('ix_due_diligence_reports_ngo_id'), table_name='due_diligence_reports')
    op.drop_table('due_diligence_reports')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_optimization_runs_status'), table_name='optimization_runs')
    op.drop_index(op.f('ix_optimization_runs_public_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_ngos_name'), table_name='ngos')
    op.drop_index(op.f('ix_ngos_external_id'), table_name='ngos')
    op.drop_table('ngos')
    op.drop_index(op.f('ix_audit_events_run_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_public_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
